### ISSUE TITLE
Saturates memory on large corpus

### ISSUE THREAD

**Issue by jjhbw** [soaxelbrooke/phrase#18]
Hi! This looks like a great tool. I love that it's focused on command line use.

When I took it for a spin on a larger-than-memory corpus the process got killed because of being OOM.

Is this expected behaviour? (I respect that working with larger-than-memory datasets is complicated in general)

**Comment by soaxelbrooke** [comment]
Hey @jjhbw, thanks for submitting this! Yes, I'm planning on adding a streaming mode very soon - currently it eagerly loads the data source, so a larger than memory dataset will always cause it to OOM.  The update I'm planning will simple chunk these into reasonable sizes (maybe 10^5 to 10^6 documents) and perform count updates per batch.  This will allow larger than memory corpora and persistent streaming from stdin.

**Comment by soaxelbrooke** [comment]
Hey @jjhbw, I added the doc batching, let me know if it works for you! Here's the release with it:

https://github.com/soaxelbrooke/phrase/releases/tag/0.3.4

**Comment by jjhbw** [comment]
That was fast! Yes, batch mode seems to do the trick! It is working through my dataset now, i'll let you know if I run in to anything unexpected.
